name: 需求建议（使用中文）
description: 新功能、建议等
labels: ['建议']
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 在提问之前...
      description: 您在此处发布新 Issue 会导致全体开发者的电子邮箱收到一封提醒邮件，请通过确认以下条目以节省所有人的时间。
      options:
      - label: 我基本确定这是一个新功能/建议，而不是遇到了 bug。bug请在“错误”类别中反馈
        required: true
      - label: 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速理解我所提出的建议
        required: true
      - label: 我已在未仔细阅读这些内容的情况下勾选所有选项，并相信这不会影响问题的处理
        required: false
  - type: textarea
    id: describe
    attributes:
      label: 说说你遇到的问题？
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: 有什么好的想法？
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: 其他内容
      description: 关于该需求建议的任何其他背景或屏幕截图。
    validations:
      required: false