name: Beta Build LimbusLocalize
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * 2'
jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('src/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Run build script
        run: |
          ./build.ps1 Beta
      - name: Upload Full
        uses: actions/upload-artifact@v3
        with:
          name: LimbusLocalize_Beta.7z
          path: Release/LimbusLocalize_Beta.7z
      - name: Upload OTA
        uses: actions/upload-artifact@v3
        with:
          name: LimbusLocalize_OTA_Beta.7z
          path: Release/LimbusLocalize_OTA_Beta.7z
