name: mirrorchyan_release_note

on:
  workflow_dispatch:
  release:
    types: [released, edited]

jobs:
  mirrorchyan:
    runs-on: macos-latest

    steps:
      - id: uploading
        uses: MirrorChyan/release-note-action@v1
        with:
          mirrorchyan_rid: LLC

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: LocalizeLimbusCompany
          repo: LocalizeLimbusCompany
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
