name: mirrorchyan_font

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "Fonts/LLCCN-Font.7z"

jobs:
  upload_font:
    runs-on: macos-latest
    steps:
      - name: Cancel run if not owner
        if: ${{ github.repository_owner != 'LocalizeLimbusCompany' }}
        uses: andymckay/cancel-action@master

      - uses: actions/checkout@v4

      - name: Version Name
        id: version_name
        run: |
          version=$(git rev-parse HEAD)
          release_note=$(git log --pretty=format:"%ad %h %s" --date=iso -1)

          echo "version=$version" | tee -a "$GITHUB_OUTPUT"
          echo "release_note=$release_note" | tee -a "$GITHUB_OUTPUT"

      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: local
          mirrorchyan_rid: LLCCN-Font
          filename: Fonts/LLCCN-Font.7z
          version_name: ${{ steps.version_name.outputs.version }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}

      - uses: MirrorChyan/release-note-action@v1
        with:
          mirrorchyan_rid: LLCCN-Font

          version_name: ${{ steps.version_name.outputs.version }}
          release_note: ${{ steps.version_name.outputs.release_note }}
          
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
