name: mirrorchyan_release

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  mirrorchyan:
    runs-on: macos-latest

    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "LimbusLocalize_*.7z"
          p7zip: true
          mirrorchyan_rid: LLC

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: LocalizeLimbusCompany
          repo: LocalizeLimbusCompany
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
